### ISSUE TITLE
BYSTANDER INFO

### ISSUE THREAD

**Issue by Amawers** [SIPIAR-CAPSTONE/admin#16]
**bystander info issue sa date verified why invalid date. Ang date verified sa bystanders dapat naay date jud, if not verified dapat ibutang nga not verified. (ADMIN) - ang issue ani kay ang data na ghe butang nimo sa date verified is ang ng verification request time. walay date verified sa supabase.**

**Comment by Verseler** [comment]
@Amawers na sulbad na nimo ni?
naa koy solution ani
